[project]
name = "autograd"
version = "0.1.0"
description = "Automatic differentiation library"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "graphviz>=0.21",
    "matplotlib>=3.10.9",
]

[build-system]
requires = ["setuptools>=78"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
py-modules = ["autograd", "vis"]

[dependency-groups]
dev = [
    "pytest>=9.0.3",
]
